/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentSecretaryRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.GovernmentSecretaryOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GovernmentFundRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import userinterface.LoginJPanel;

/**
 *
 
 */
public class GovernmentSecretaryWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentSecretaryWorkAreaJPanel
     */
    private JPanel jPanel;
    private UserAccount userAccount;
    private GovernmentSecretaryOrganization secretaryOrganization;
    private Enterprise enterprise;
    private DB4OUtil dB4OUtil;
    private EcoSystem ecoSystem;
    
    public GovernmentSecretaryWorkAreaJPanel(JPanel jpanel, UserAccount userAccount, Organization organization, Enterprise enterprise, DB4OUtil dB4OUtil,EcoSystem ecosystem) {
        initComponents();
        this.enterprise = enterprise;
        this.jPanel = jpanel;
        this.secretaryOrganization = (GovernmentSecretaryOrganization) organization;
        this.userAccount = userAccount;
        this.ecoSystem=ecosystem;
        this.dB4OUtil = dB4OUtil;
        valueLabel1.setText(enterprise.getName());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        btnLogoutPatient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        valueLabel1 = new javax.swing.JLabel();
        btnAssign = new javax.swing.JButton();
        btnCompleteDelivery = new javax.swing.JButton();
        enterpriseLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(207, 207, 207));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestJTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Amount", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 1070, 370));

        btnLogoutPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogoutPatient.setText("Logout");
        btnLogoutPatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutPatientMouseExited(evt);
            }
        });
        btnLogoutPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPatientActionPerformed(evt);
            }
        });
        add(btnLogoutPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(1082, 10, -1, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SECRETARY WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 6, 430, -1));

        enterpriseLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel1.setText("Secretary Work Queue");
        add(enterpriseLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, -1, -1));

        valueLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        valueLabel1.setText("<value>");
        add(valueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        btnAssign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAssign.setText("Assign to Me");
        btnAssign.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAssignFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAssignFocusLost(evt);
            }
        });
        btnAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignMouseExited(evt);
            }
        });
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 216, 36));

        btnCompleteDelivery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCompleteDelivery.setText("Process Request");
        btnCompleteDelivery.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnCompleteDeliveryFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCompleteDeliveryFocusLost(evt);
            }
        });
        btnCompleteDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompleteDeliveryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompleteDeliveryMouseExited(evt);
            }
        });
        btnCompleteDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteDeliveryActionPerformed(evt);
            }
        });
        add(btnCompleteDelivery, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, 216, 36));

        enterpriseLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        enterpriseLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        enterpriseLabel2.setText("Enterprise :");
        add(enterpriseLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutPatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseEntered
        // TODO add your handling code here:
//        btnLogoutPatient.setForeground(new Color(255, 255, 255));
//        btnLogoutPatient.setBackground(new Color(158, 33, 50));
    }//GEN-LAST:event_btnLogoutPatientMouseEntered

    private void btnLogoutPatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutPatientMouseExited
        // TODO add your handling code here:
//        btnLogoutPatient.setForeground(new Color(188, 188, 188));
//        btnLogoutPatient.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnLogoutPatientMouseExited

    private void btnLogoutPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPatientActionPerformed
        // TODO add your handling code here:

        jPanel.removeAll();
        LoginJPanel lp = new LoginJPanel(ecoSystem, dB4OUtil, jPanel);
        jPanel.add("LoginJPanel", lp);
        CardLayout crdLyt = (CardLayout) jPanel.getLayout();
        crdLyt.next(jPanel);
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_btnLogoutPatientActionPerformed

    private void btnAssignFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAssignFocusGained
        // TODO add your handling code here:
//        btnAssign.setForeground(new Color(255, 255, 255));
//        btnAssign.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAssignFocusGained

    private void btnAssignFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAssignFocusLost
        // TODO add your handling code here:
//        btnAssign.setForeground(new Color(188, 188, 188));
//        btnAssign.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAssignFocusLost

    private void btnAssignMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignMouseEntered
        // TODO add your handling code here:
//        btnAssign.setForeground(new Color(255, 255, 255));
//        btnAssign.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnAssignMouseEntered

    private void btnAssignMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignMouseExited
        // TODO add your handling code here:
//        btnAssign.setForeground(new Color(188, 188, 188));
//        btnAssign.setBackground(new Color(13, 17, 23));
    }//GEN-LAST:event_btnAssignMouseExited

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            WorkRequest request = (GovernmentFundRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if (request.getStatus().equals("Sent to Secretary")) {
                request.setReceiver(userAccount);
                request.setStatus("Pending on " + request.getReceiver().getEmployee().getEmpName());
                populateTable();
                JOptionPane.showMessageDialog(null, "Success !! Request is assigned to you ");
            } else {
                JOptionPane.showMessageDialog(null, "Can't assign this work request, as the work request is in " + request.getStatus() + " status", "Warning!", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnCompleteDeliveryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryFocusGained
        // TODO add your handling code here:
//        btnCompleteDelivery.setForeground(new Color(255, 255, 255));
//        btnCompleteDelivery.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCompleteDeliveryFocusGained

    private void btnCompleteDeliveryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryFocusLost
        // TODO add your handling code here:
//        btnCompleteDelivery.setForeground(new Color(188, 188, 188));
//        btnCompleteDelivery.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnCompleteDeliveryFocusLost

    private void btnCompleteDeliveryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryMouseEntered
        // TODO add your handling code here:
//        btnCompleteDelivery.setForeground(new Color(255, 255, 255));
//        btnCompleteDelivery.setBackground(new Color(144, 202, 249));
    }//GEN-LAST:event_btnCompleteDeliveryMouseEntered

    private void btnCompleteDeliveryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryMouseExited
        // TODO add your handling code here:
//        btnCompleteDelivery.setForeground(new Color(188, 188, 188));
//        btnCompleteDelivery.setBackground(new Color(22, 27, 34));
    }//GEN-LAST:event_btnCompleteDeliveryMouseExited

    private void btnCompleteDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteDeliveryActionPerformed
        // TODO add your handling code here:

        int selectedRow = workRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first from the table to view details");
            return;
        } else {
            GovernmentFundRequest fundRequest = (GovernmentFundRequest) workRequestJTable.getValueAt(selectedRow, 0);
            if (fundRequest.getStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Cannot process a Rejected Request", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (fundRequest.getStatus().equalsIgnoreCase("Sent to Treasurer")) {
                JOptionPane.showMessageDialog(null, "Request already processed", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (fundRequest.getStatus().equalsIgnoreCase("Sent to Secretary")) {
                JOptionPane.showMessageDialog(null, "Please assign selected request first");
                return;
            }
            if (!userAccount.equals(fundRequest.getReceiver())) {
                JOptionPane.showMessageDialog(null, "Not Authorized", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (!userAccount.getEmployee().equals(fundRequest.getReceiver().getEmployee())) {
                JOptionPane.showMessageDialog(null, "Request assigned to other Officer", "Warning!", JOptionPane.WARNING_MESSAGE);
                return;
            }

            GovernmentSecretaryProcessWorkRequestJPanel panel = new GovernmentSecretaryProcessWorkRequestJPanel(jPanel, userAccount, fundRequest, enterprise);
            jPanel.add("secretaryProcessWorkRequestJPanel", panel);
            CardLayout layout = (CardLayout) jPanel.getLayout();
            layout.next(jPanel);

        }
    }//GEN-LAST:event_btnCompleteDeliveryActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();

        model.setRowCount(0);

        for (WorkRequest request : secretaryOrganization.getWorkQueue().getWorkRequests()) {
            String status = request.getStatus();
            Object[] row = new Object[6];
            row[0] = ((GovernmentFundRequest) request);
            row[1] = request.getSender().getEmployee().getEmpName();
            if (status.equalsIgnoreCase("Sent to Treasurer") || status.equalsIgnoreCase("Sent to Secretary")) {
                row[2] = null;
            } else {
                row[2] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getEmpName();
            }
            row[3] = status;
            row[4] = ((GovernmentFundRequest) request).getRequestAmount();
            row[5] = ((GovernmentFundRequest) request).getMessage();

            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        workRequestJTable.setRowSorter(sorter);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCompleteDelivery;
    private javax.swing.JButton btnLogoutPatient;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valueLabel1;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
